version: '3.8'

services:
 tensorflow:
  build: .
  ports:
   - 8080:8080
  volumes:
   - .:/triangle_model
  tty: true
  deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]